let tvShows = [
  "Seinfeld",
  "Friends",
  "The Simpsons",
  "South Park",
  "Inspector Morse",
  "Endeavour",
  "Frost",
  "Sherlock",
  "Twilight Zone",
  "Law and Order",
  "Columbo",
  "Fargo",
  "The Thick of It",
  "VEEP",
  "Curb Your Enthusiasm",
  "Twin Peaks",
  "The X-Files",
  "Frasier",
  "Mad Men",
  "The Sopranos",
  "The Killing",
  "The West Wing",
  "Homeland",
  "Saturday Night Live",
  "House of Cards",
  "The Wonder Years",
  "Dexter",
  "Cheers",
  "Star Trek - TOS",
  "M*A*S*H",
  "Luther",
  "Alfred Hitchcock Presents",
  "El Chapo",
  "Narcos",
  "True Detective",
  "Agatha Christie's Poirot",
  "Modern Family",
  "Married With Children",
  "That 70's show",
  "Yes Minister",
  "Yes Prime Minister",
  "The King of Queens",
  "Just Shoot Me!",
  "Newsradio",
  "Hannibal",
  "The Terror",
  "The Fall"
];

export default tvShows;
